name: Test
on:
  workflow_dispatch:
  pull_request_target:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run tests
        run: |
          npm ci
          npm run build
          npm run test
